#pragma once

#define ROOT_APP_DIRECTORY				"./"
#define ROOT_APP_TEXTURES_DIRECTORY		ROOT_APP_DIRECTORY"Textures/"
#define OUTPUT_SRTM3_ROOT_FOLDER		ROOT_APP_DIRECTORY"Terrain/"
#define OUTPUT_SRTM3_ROOT_FOLDER_CACHE	OUTPUT_SRTM3_ROOT_FOLDER"Cache/"
#define OUTPUT_IMAGE_ROOT_FOLDER		OUTPUT_SRTM3_ROOT_FOLDER"Textures/"
#define OUTPUT_AIRCRAFT_ROOT_FOLDER		ROOT_APP_DIRECTORY"Models/"
